### ISSUE TITLE
Raising numbers to the power of 1 or Multiplying by 1 returns 1

### ISSUE THREAD

**Issue by yunfeizhengcoder** [VirxEC/CalcPlus#10]
**Describe the bug**
(Using exponent function)
2^1 = 1
3^1 = 1
4^1 = 1
(Using multiplication)
1 *4 = 1
1 *3 = 1
1  *  2 = 1
The bug doesn't appear if 1 is in the 2nd input field, 4 * 1 = 4.

**Comment by VirxEC** [comment]
Fixed :)

**Comment by VirxEC** [comment]
Exponents still doesn't work :(

**Comment by VirxEC** [comment]
All is good now :100:
