### ISSUE TITLE
Multiplying by 0 instead multiplies by 2 if 0 is in the first input field

### ISSUE THREAD

**Issue by yunfeizhengcoder** [VirxEC/CalcPlus#11]
**Describe the bug**
when multiplying by 0 it doesn't work, it multiplies by 2 instead
0 * 0 = 0
0 * 1 = 2
0 * 2 = 4
0 * 3 = 6
Multiplication by 0 works if 0 is in the 2nd input field

**Comment by VirxEC** [comment]
Fixed :)
