### ISSUE TITLE
Negative integers cannot be raised to powers

### ISSUE THREAD

**Issue by yunfeizhengcoder** [VirxEC/CalcPlus#15]
**Describe the bug**
(-1) ^ 1 = 1- (negative sign after the 1)

(-1) ^ 2 = NaNNaNNaN...
it just doesn't work with any negative integer

Only thing that does work is (-1) ^ 0 = 1, etc.

**Comment by VirxEC** [comment]
idk what happened, but now:
(-1) ^ 1 = 1-
and
(-1) ^ 2 = infinite loop :(

**Comment by VirxEC** [comment]
(-1) ^ 0 = 1 (Correct)
(-1) ^ 1 = 1 (Incorrect)
(-1) ^ 2 = NaN2 (Incorrect)

**Comment by VirxEC** [comment]
(-1) ^ 1 = -1

**Comment by VirxEC** [comment]
(-1) ^ 2 = 1
but
2 ^ 64 = 16

**Comment by VirxEC** [comment]
Fixed
