### ISSUE TITLE
Multiple decimal points in multiplication

### ISSUE THREAD

**Issue by yunfeizhengcoder** [VirxEC/CalcPlus#16]
**Describe the bug**

0.01 * 0.1 = 0.0.1
0.001 * 0.01 = 0..1
0.1 * 0.01 = 0.1
0.01 * 0.001 = 0.1

**Comment by VirxEC** [comment]
This appears to be a bug with the fundamentals of the multiplication function. I am currently re-writing it. The new algorithm will be faster and more accurate. I have already fixed this bug, but there are other bugs like:
```1000000000000 * 10000 = 1000000000000```
instead of
```1000000000000 * 10000 = 10000000000000000```

**Comment by VirxEC** [comment]
If you want to take a look at the progress, here:
https://repl.it/@VirxEC/CalcPlus

**Comment by VirxEC** [comment]
Fixed numbers not carrying over

**Comment by VirxEC** [comment]
`2^64` now works, but `2.2*2.2` doesn't. It results in `0.88` instead of `4.84`.

**Comment by VirxEC** [comment]
Issue has been fixed
