### ISSUE TITLE
Multiplication & Decimals

### ISSUE THREAD

**Issue by yunfeizhengcoder** [VirxEC/CalcPlus#5]
**Describe the bug**
When using the multiplication option with decimals, the resulting output doesn't have the right decimal places. e.g. 8 * 1.5 = 1.2, 9 * 1.5 = 1.35

**Platform (please complete the following information):**
 - Device: Windows 7
 - Browser: Chrome

**Comment by VirxEC** [comment]
This issue has been fixed :)
