### ISSUE TITLE
Multiplying negative numbers does not work

### ISSUE THREAD

**Issue by yunfeizhengcoder** [VirxEC/CalcPlus#9]
**Describe the bug**
3 * -2  = -4
3 * -3 = -6
4 * -3.5 = -7
(-1.5) * (-3.5) = -7
(-2) * 3 = --6 ( two negative signs)
(-5) * 5 = --25

**Comment by VirxEC** [comment]
Bug is now 1/2 fixed - only bugs like 4 * -3.5 = -7 exist, but now it equals -1.4 so I just have to fix the decimal calculation and this issue is done. (-1.5) * (-3.5) also equals 52.5 instead of 5.25, again, just have to fix decimal calculations.

**Comment by VirxEC** [comment]
Fixed :)
